### ISSUE TITLE
Merging GraphML "Could not find starting node for edge"

### ISSUE THREAD

**Issue by ghost** [KristianKarl-zz/GraphWalker#1]
Hi. I am trying to use GraphWalker CLI to merge graphml files from another program. I have tried two different graphml-generating tools (NodeXL and Pajek) and a manually-written graphml file and the results unfortunately are the same. The issue appears to be some sort of problem finding nodes. I did look to confirm the nodes exist, of course. Any ideas?

Log:

2011-10-05 18:09:17,062 [Thread-1] WARN  - Trying to retrieve verbose statistics without specifying machine
2011-10-05 18:09:17,063 [Thread-1] INFO  - 
2011-10-05 18:09:30,779 [main] ERROR - Could not find starting node for edge. Name: 'softartisans' In file 'c:\SPTweets\sharepointcollector_2011-10-05_16-29-46.graphml'
2011-10-05 18:09:30,791 [main] ERROR - java.lang.RuntimeException: Could not parse file: 'c:\SPTweets\sharepointcollector_2011-10-05_16-29-46.graphml'. Could not find starting node for edge. Name: 'softartisans' In file 'c:\SPTweets\sharepointcollector_2011-10-05_16-29-46.graphml'
    at org.graphwalker.io.GraphML.parseFile(GraphML.java:395)
    at org.graphwalker.io.GraphML.load(GraphML.java:121)
    at org.graphwalker.ModelBasedTesting.readGraph(ModelBasedTesting.java:502)
    at org.graphwalker.CLI.RunCommandMerge(CLI.java:967)
    at org.graphwalker.CLI.run(CLI.java:252)
    at org.graphwalker.CLI.main(CLI.java:165)

**Comment by KristianKarl-zz** [comment]
Hi,

Could you send me the graphml files you're trying to merge? 
Since we can't attache files to issues in github, could you send them to: kristian.hermann.karl @ gmail com

/Kristian

**Comment by KristianKarl-zz** [comment]
Ooops, pressed the wrong button.
